### ISSUE TITLE
Encoding: л in Potentiлle beroepsbevolking 15-64

### ISSUE THREAD

**Issue by jsoetendal** [Amsterdam/bbga#1]
In https://api.data.amsterdam.nl/bbga/meta/ staat bij de o.a. variabele BEVPOTBBV15_64 in het label-veld een л ipv ë bij "Potentiлle beroepsbevolking 15-64"

**Comment by spreeker** [comment]
should be fixed with 8987d8b2c4605d6566ff1c6b092dd782148bcf38  tomorrow visisble in acc and in two days in prodution.
